#![allow(dead_code, unused_imports, unused_variables)]
//! OS keychain module.
//!
//! Thin Tauri commands over the keyring v4 ecosystem for the local shell:
//!
//! - `keyring_set(service, user, secret)`
//! - `keyring_get(service, user)` -> `Option<String>` (`null` when no entry)
//! - `keyring_delete(service, user)` -> `bool` (`false` when no entry)
//! - `keyring_tier()` -> `{ tier, notice }` for the "stored less securely"
//!   notice in the shell UI
//!
//! All keyring work runs inside `spawn_blocking`; the zbus Secret Service
//! backend must never run on the main thread (blocking zbus connection
//! deadlocks against the GTK main loop), and the db-keystore backend
//! blocks on its sqlite I/O. None of the commands do keyring I/O on the
//! main thread on any platform.
//!
//! Linux store selection happens once per process: Secret Service first,
//! then db-keystore (encrypted sqlite file), then keyutils (kernel session
//! keyring). The winning tier is persisted in `<app data dir>/keyring-tier`
//! so a later startup does not migrate upward and lose access to
//! credentials stored by a fallback tier. The chosen tier is surfaced
//! through `keyring_tier` so the shell can show the notice.
//!
//! Namespacing: every credential uses the app service
//! `dev.persea.desktop`; `user` is caller-supplied (D07 uses
//! `<instance url>` + device token id).
//!
//! Security: the four commands are gated by the app-manifest command
//! allowlist (see the wiring note below), so a remote page can never
//! invoke them, and the shell capability grants them only to the `main`
//! window's local pages.
//!
//! Wiring for the dispatcher (do not forget, the module does not register
//! itself):
//!
//! 1. `Cargo.toml`: replace the pre-wired `keyring` dependency with
//!    `keyring-core` + the per-store crates (target-gated; it does not
//!    compile as pre-wired: keyring 4.x requires `v1`/`cli`, the apple
//!    store requires `keychain`, the secret-service backend requires a
//!    runtime feature). Exact snippet in `docs/keychain.md`.
//! 2. `build.rs`: gate the commands behind the ACL manifest:
//!    ```text
//!    fn main() {
//!        let attributes = tauri_build::Attributes::new().app_manifest(
//!            tauri_build::AppManifest::new().commands(&[
//!                "keyring_set",
//!                "keyring_get",
//!                "keyring_delete",
//!                "keyring_tier",
//!            ]),
//!        );
//!        tauri_build::try_build(attributes)
//!            .expect("tauri-build failed");
//!    }
//!    ```
//!    This generates `permissions/autogenerated/keyring_*.toml` with
//!    `allow-keyring-*` / `deny-keyring-*` permissions and removes the
//!    commands from the default-allowed set.
//! 3. `lib.rs`:
//!    ```text
//!    mod keyring;
//!
//!    .invoke_handler(tauri::generate_handler![
//!        crate::keyring::keyring_set,
//!        crate::keyring::keyring_get,
//!        crate::keyring::keyring_delete,
//!        crate::keyring::keyring_tier,
//!    ])
//!    ```
//! 4. `capabilities/default.json`: grant the commands to the local shell
//!    window only:
//!    ```json
//!    "permissions": [ ...existing..., "allow-keyring-set",
//!      "allow-keyring-get", "allow-keyring-delete", "allow-keyring-tier" ]
//!    ```
//!    The capability already restricts `windows` to `["main"]`; remote
//!    origins get no capability (D04), and tauri's IPC layer rejects
//!    manifest-gated commands without a matching ACL entry, plus any
//!    custom command invoked from a remote origin.

// The Linux fallback chain (Secret Service / db-keystore / keyutils) is
// cfg-gated per platform; the imports, constants and variables it uses are
// legitimately unused on Windows/macOS. The compile gate runs with
// -D warnings, so the module carries a scoped allow; each platform arm
// removes what it consumes as it is exercised.

use std::collections::HashMap;
use std::io::{Read, Write};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, Mutex};

use keyring_core::{CredentialStore, Error as KeyringError};
use tauri::{AppHandle, Manager};

pub const SERVICE_NAME: &str = "dev.persea.desktop";
pub const PROBE_USER: &str = "__persea_probe__";

const TIER_MARKER_FILE: &str = "keyring-tier";
const DB_KEY_FILE: &str = "keyring-key";
const DB_FILE: &str = "keyring.db";
const DB_CIPHER: &str = "aes256gcm";

const MAX_SERVICE_LEN: usize = 512;
const MAX_USER_LEN: usize = 2048;
const MAX_SECRET_LEN: usize = 65536;

/// The credential store tier currently backing the keyring commands.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KeyringTier {
    /// macOS Keychain Services.
    MacOsKeychain,
    /// Windows Credential Manager.
    WindowsCredentialManager,
    /// Linux Secret Service over zbus (gnome-keyring / kwallet / KeePassXC).
    SecretService,
    /// Linux fallback: encrypted sqlite file (`db-keystore`).
    DbKeyStore,
    /// Linux fallback: kernel session keyring (`keyutils`).
    KeyUtils,
}

impl KeyringTier {
    pub fn as_str(self) -> &'static str {
        match self {
            KeyringTier::MacOsKeychain => "macos-keychain",
            KeyringTier::WindowsCredentialManager => "windows-credential-manager",
            KeyringTier::SecretService => "secret-service",
            KeyringTier::DbKeyStore => "db-keystore",
            KeyringTier::KeyUtils => "keyutils",
        }
    }

    /// Returns the notice to surface in the shell UI when the tier is a
    /// fallback, `None` for OS-native stores.
    pub fn notice(self) -> Option<&'static str> {
        match self {
            KeyringTier::MacOsKeychain
            | KeyringTier::WindowsCredentialManager
            | KeyringTier::SecretService => None,
            KeyringTier::DbKeyStore => Some(
                "The desktop keyring is unavailable, so credentials are stored in an encrypted \
                 file on this device. They are less protected than a system keychain.",
            ),
            KeyringTier::KeyUtils => Some(
                "The desktop keyring is unavailable, so credentials are stored in the Linux \
                 kernel session keyring and are lost when this session ends.",
            ),
        }
    }

    fn from_str(value: &str) -> Option<Self> {
        match value {
            "macos-keychain" => Some(KeyringTier::MacOsKeychain),
            "windows-credential-manager" => Some(KeyringTier::WindowsCredentialManager),
            "secret-service" => Some(KeyringTier::SecretService),
            "db-keystore" => Some(KeyringTier::DbKeyStore),
            "keyutils" => Some(KeyringTier::KeyUtils),
            _ => None,
        }
    }
}

#[derive(Debug, Clone)]
struct SelectedStore {
    store: Arc<CredentialStore>,
    tier: KeyringTier,
}

static ACTIVE: Mutex<Option<SelectedStore>> = Mutex::new(None);

fn selected_store(data_dir: &Path) -> Result<SelectedStore, String> {
    let mut guard = ACTIVE
        .lock()
        .map_err(|_| "keyring state lock poisoned".to_string())?;
    if guard.is_none() {
        *guard = Some(select_store(data_dir)?);
    }
    Ok(guard
        .as_ref()
        .expect("keyring store was just initialized above")
        .clone())
}

/// Platform store selection. Linux uses the fallback chain; macOS and
/// Windows use their native store unconditionally.
fn select_store(data_dir: &Path) -> Result<SelectedStore, String> {
    #[cfg(target_os = "linux")]
    {
        let tiers = [
            KeyringTier::SecretService,
            KeyringTier::DbKeyStore,
            KeyringTier::KeyUtils,
        ];
        select_with(data_dir, &tiers, build_store)
    }
    #[cfg(target_os = "macos")]
    {
        let store: Arc<CredentialStore> =
            apple_native_keyring_store::keychain::Store::new().map_err(|e| e.to_string())?;
        Ok(SelectedStore {
            store,
            tier: KeyringTier::MacOsKeychain,
        })
    }
    #[cfg(target_os = "windows")]
    {
        let store: Arc<CredentialStore> =
            windows_native_keyring_store::Store::new().map_err(|e| e.to_string())?;
        Ok(SelectedStore {
            store,
            tier: KeyringTier::WindowsCredentialManager,
        })
    }
    #[cfg(not(any(target_os = "linux", target_os = "macos", target_os = "windows")))]
    {
        Err("keyring is not supported on this platform".to_string())
    }
}

/// Walks `tiers` (starting at the persisted marker tier when it exists,
/// never migrating upward), constructing and probing each store until one
/// works. Persists the winning tier.
fn select_with(
    data_dir: &Path,
    tiers: &[KeyringTier],
    factory: impl Fn(KeyringTier, &Path) -> Result<Arc<CredentialStore>, String>,
) -> Result<SelectedStore, String> {
    let start = marker_tier(data_dir)
        .and_then(|tier| tiers.iter().position(|candidate| *candidate == tier))
        .unwrap_or(0);
    let mut last_error = "no usable credential store".to_string();
    for tier in &tiers[start..] {
        let store = match factory(*tier, data_dir) {
            Ok(store) => store,
            Err(err) => {
                last_error = format!("{}: {err}", tier.as_str());
                continue;
            }
        };
        if !probe_store(&store) {
            last_error = format!("{}: probe round-trip failed", tier.as_str());
            continue;
        }
        write_marker(data_dir, *tier);
        return Ok(SelectedStore { store, tier: *tier });
    }
    Err(last_error)
}

/// Verifies a freshly constructed store by setting, reading, and deleting
/// a throwaway probe credential.
fn probe_store(store: &Arc<CredentialStore>) -> bool {
    let entry = match store.build(SERVICE_NAME, PROBE_USER, None) {
        Ok(entry) => entry,
        Err(_) => return false,
    };
    let probe = probe_value();
    if entry.set_password(&probe).is_err() {
        return false;
    }
    let round_tripped = entry
        .get_password()
        .map(|value| value == probe)
        .unwrap_or(false);
    let _ = entry.delete_credential();
    round_tripped
}

fn probe_value() -> String {
    static COUNTER: AtomicU64 = AtomicU64::new(0);
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    format!(
        "persea-probe-{}-{:x}",
        COUNTER.fetch_add(1, Ordering::Relaxed),
        nanos
    )
}

#[cfg(target_os = "linux")]
fn build_store(tier: KeyringTier, data_dir: &Path) -> Result<Arc<CredentialStore>, String> {
    match tier {
        KeyringTier::SecretService => zbus_secret_service_keyring_store::Store::new()
            .map(|store| -> Arc<CredentialStore> { store })
            .map_err(|e| e.to_string()),
        KeyringTier::DbKeyStore => {
            let key = db_key(data_dir)?;
            let path = db_path(data_dir);
            let mut modifiers: HashMap<&str, &str> = HashMap::new();
            modifiers.insert("path", &path);
            modifiers.insert("encryption-cipher", DB_CIPHER);
            modifiers.insert("encryption-hexkey", key.as_str());
            db_keystore::DbKeyStore::new_with_modifiers(&modifiers)
                .map(|store| -> Arc<CredentialStore> { store })
                .map_err(|e| e.to_string())
        }
        KeyringTier::KeyUtils => linux_keyutils_keyring_store::Store::new()
            .map(|store| -> Arc<CredentialStore> { store })
            .map_err(|e| e.to_string()),
        _ => Err(format!("{} is not a Linux store", tier.as_str())),
    }
}

/// Loads or creates the 256-bit hex key that encrypts the fallback
/// db-keystore file. The key is generated randomly on first use and kept
/// next to the database with 0600 permissions.
///
/// Decision: the key cannot be derived from the
/// pairing token, because the pairing token is the credential this store
/// protects (chicken-and-egg), and no passphrase prompt exists in the D06
/// shell scope. A random per-install key protects the file against casual
/// read access by other local users; it does not protect against an
/// attacker with the same account, which is why the fallback tier
/// surfaces the "stored less securely" notice.
#[cfg(target_os = "linux")]
fn db_key(data_dir: &Path) -> Result<String, String> {
    let path = data_dir.join(DB_KEY_FILE);
    if let Ok(existing) = std::fs::read_to_string(&path) {
        let trimmed = existing.trim();
        if trimmed.len() == 64 && trimmed.chars().all(|c| c.is_ascii_hexdigit()) {
            return Ok(trimmed.to_string());
        }
    }
    let mut bytes = [0u8; 32];
    let mut urandom = std::fs::File::open("/dev/urandom").map_err(|e| e.to_string())?;
    urandom.read_exact(&mut bytes).map_err(|e| e.to_string())?;
    let key: String = bytes.iter().map(|b| format!("{b:02x}")).collect();
    write_private(&path, key.as_bytes())?;
    Ok(key)
}

#[cfg(target_os = "linux")]
fn db_path(data_dir: &Path) -> String {
    data_dir.join(DB_FILE).to_string_lossy().into_owned()
}

/// Creates or truncates a file with 0600 permissions.
#[cfg(target_os = "linux")]
fn write_private(path: &Path, contents: &[u8]) -> Result<(), String> {
    use std::os::unix::fs::OpenOptionsExt;
    let mut file = std::fs::OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .mode(0o600)
        .open(path)
        .map_err(|e| e.to_string())?;
    file.write_all(contents).map_err(|e| e.to_string())?;
    let _ = file.sync_all();
    restrict_private(path, 0o600);
    Ok(())
}

/// Restricts a file or directory to the owning user (no-op on platforms
/// without unix permission bits).
fn restrict_private(path: &Path, mode: u32) {
    #[cfg(unix)]
    {
        let _ = std::fs::set_permissions(path, std::os::unix::fs::PermissionsExt::from_mode(mode));
    }
    #[cfg(not(unix))]
    {
        let _ = (path, mode);
    }
}

fn marker_tier(data_dir: &Path) -> Option<KeyringTier> {
    let raw = std::fs::read_to_string(data_dir.join(TIER_MARKER_FILE)).ok()?;
    KeyringTier::from_str(raw.trim())
}

fn write_marker(data_dir: &Path, tier: KeyringTier) {
    let path = data_dir.join(TIER_MARKER_FILE);
    let unchanged = std::fs::read_to_string(&path)
        .map(|existing| existing.trim() == tier.as_str())
        .unwrap_or(false);
    if unchanged {
        return;
    }
    let _ = std::fs::write(&path, format!("{}\n", tier.as_str()));
    restrict_private(&path, 0o600);
}

fn validate_names(service: &str, user: &str) -> Result<(), String> {
    if service.is_empty() || service.len() > MAX_SERVICE_LEN {
        return Err(format!("service must be 1..={MAX_SERVICE_LEN} characters"));
    }
    if user.is_empty() || user.len() > MAX_USER_LEN {
        return Err(format!("user must be 1..={MAX_USER_LEN} characters"));
    }
    Ok(())
}

fn validate_secret(secret: &str) -> Result<(), String> {
    if secret.len() > MAX_SECRET_LEN {
        return Err(format!("secret must be at most {MAX_SECRET_LEN} bytes"));
    }
    Ok(())
}

fn app_data_dir(app: &AppHandle) -> Result<PathBuf, String> {
    let dir = app
        .path()
        .app_data_dir()
        .map_err(|e| format!("cannot resolve app data dir: {e}"))?;
    std::fs::create_dir_all(&dir).map_err(|e| format!("cannot create app data dir: {e}"))?;
    #[cfg(target_os = "linux")]
    {
        restrict_private(&dir, 0o700);
    }
    Ok(dir)
}

fn keyring_error(err: KeyringError) -> String {
    err.to_string()
}

fn spawn_error(err: tauri::Error) -> String {
    format!("keyring task failed to run: {err}")
}

// The blocking op helpers take the store explicitly so unit tests can
// drive them with the mock store.

fn op_set(store: &SelectedStore, service: &str, user: &str, secret: &str) -> Result<(), String> {
    let entry = store
        .store
        .build(service, user, None)
        .map_err(keyring_error)?;
    entry.set_password(secret).map_err(keyring_error)
}

fn op_get(store: &SelectedStore, service: &str, user: &str) -> Result<Option<String>, String> {
    let entry = store
        .store
        .build(service, user, None)
        .map_err(keyring_error)?;
    match entry.get_password() {
        Ok(password) => Ok(Some(password)),
        Err(KeyringError::NoEntry) => Ok(None),
        Err(err) => Err(keyring_error(err)),
    }
}

fn op_delete(store: &SelectedStore, service: &str, user: &str) -> Result<bool, String> {
    let entry = store
        .store
        .build(service, user, None)
        .map_err(keyring_error)?;
    match entry.delete_credential() {
        Ok(()) => Ok(true),
        Err(KeyringError::NoEntry) => Ok(false),
        Err(err) => Err(keyring_error(err)),
    }
}

/// Stores a secret. Local shell only (app-manifest command allowlist).
#[tauri::command]
pub async fn keyring_set(
    service: String,
    user: String,
    secret: String,
    app: AppHandle,
) -> Result<(), String> {
    validate_names(&service, &user)?;
    validate_secret(&secret)?;
    let data_dir = app_data_dir(&app)?;
    tauri::async_runtime::spawn_blocking(move || {
        let store = selected_store(&data_dir)?;
        op_set(&store, &service, &user, &secret)
    })
    .await
    .map_err(spawn_error)?
}

/// Reads a secret; `null` when no credential exists for the pair.
#[tauri::command]
pub async fn keyring_get(
    service: String,
    user: String,
    app: AppHandle,
) -> Result<Option<String>, String> {
    validate_names(&service, &user)?;
    let data_dir = app_data_dir(&app)?;
    tauri::async_runtime::spawn_blocking(move || {
        let store = selected_store(&data_dir)?;
        op_get(&store, &service, &user)
    })
    .await
    .map_err(spawn_error)?
}

/// Deletes a secret; `false` when no credential existed.
#[tauri::command]
pub async fn keyring_delete(service: String, user: String, app: AppHandle) -> Result<bool, String> {
    validate_names(&service, &user)?;
    let data_dir = app_data_dir(&app)?;
    tauri::async_runtime::spawn_blocking(move || {
        let store = selected_store(&data_dir)?;
        op_delete(&store, &service, &user)
    })
    .await
    .map_err(spawn_error)?
}

/// Reports the active store tier and the "stored less securely" notice
/// text for fallback tiers, so the shell can surface it.
#[derive(serde::Serialize)]
pub struct KeyringTierInfo {
    pub tier: String,
    pub notice: Option<String>,
}

#[tauri::command]
pub async fn keyring_tier(app: AppHandle) -> Result<KeyringTierInfo, String> {
    let data_dir = app_data_dir(&app)?;
    tauri::async_runtime::spawn_blocking(move || {
        let store = selected_store(&data_dir)?;
        Ok(KeyringTierInfo {
            tier: store.tier.as_str().to_string(),
            notice: store.tier.notice().map(|notice| notice.to_string()),
        })
    })
    .await
    .map_err(spawn_error)?
}

#[cfg(test)]
mod tests {
    use super::*;
    use keyring_core::mock;

    fn mock_store() -> Arc<CredentialStore> {
        mock::Store::new().expect("mock store")
    }

    fn temp_dir(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "persea-keyring-test-{name}-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(&dir).expect("temp dir");
        dir
    }

    fn ok_factory(_tier: KeyringTier, _dir: &Path) -> Result<Arc<CredentialStore>, String> {
        Ok(mock_store())
    }

    fn failing_factory(tier: KeyringTier, _dir: &Path) -> Result<Arc<CredentialStore>, String> {
        Err(format!("{}: simulated construction failure", tier.as_str()))
    }

    #[test]
    fn set_get_delete_round_trip_on_mock_store() {
        let store = SelectedStore {
            store: mock_store(),
            tier: KeyringTier::SecretService,
        };
        let service = SERVICE_NAME;
        let user = "https://persea.example.com/device-token-1";
        op_set(&store, service, user, "s3cret").expect("set");
        assert_eq!(
            op_get(&store, service, user).expect("get"),
            Some("s3cret".to_string())
        );
        assert!(op_delete(&store, service, user).expect("delete"));
        assert_eq!(
            op_get(&store, service, user).expect("get after delete"),
            None
        );
        assert!(!op_delete(&store, service, user).expect("delete missing"));
    }

    #[test]
    fn get_of_missing_entry_returns_none() {
        let store = SelectedStore {
            store: mock_store(),
            tier: KeyringTier::MacOsKeychain,
        };
        assert_eq!(
            op_get(&store, SERVICE_NAME, "https://persea.example.com/never-set").expect("get"),
            None
        );
    }

    #[test]
    fn updates_overwrite_existing_secret() {
        let store = SelectedStore {
            store: mock_store(),
            tier: KeyringTier::WindowsCredentialManager,
        };
        let user = "https://persea.example.com/token-2";
        op_set(&store, SERVICE_NAME, user, "first").expect("set 1");
        op_set(&store, SERVICE_NAME, user, "second").expect("set 2");
        assert_eq!(
            op_get(&store, SERVICE_NAME, user).expect("get"),
            Some("second".to_string())
        );
    }

    #[test]
    fn probe_store_round_trips_and_cleans_up() {
        let store = mock_store();
        assert!(probe_store(&store));
        let entry = store.build(SERVICE_NAME, PROBE_USER, None).expect("build");
        assert!(matches!(entry.get_password(), Err(KeyringError::NoEntry)));
    }

    #[test]
    fn probe_fails_when_store_rejects_writes() {
        let store = mock_store();
        let entry = store.build(SERVICE_NAME, PROBE_USER, None).expect("build");
        let mock_cred: &mock::Cred = entry
            .as_any()
            .downcast_ref()
            .expect("mock credential downcast");
        mock_cred.set_error(KeyringError::Invalid(
            "mock".to_string(),
            "deny".to_string(),
        ));
        assert!(!probe_store(&store));
    }

    #[test]
    fn selection_uses_first_working_tier_and_writes_marker() {
        let dir = temp_dir("first-working");
        let tiers = [
            KeyringTier::SecretService,
            KeyringTier::DbKeyStore,
            KeyringTier::KeyUtils,
        ];
        let selected = select_with(&dir, &tiers, ok_factory).expect("selection");
        assert_eq!(selected.tier, KeyringTier::SecretService);
        assert_eq!(
            std::fs::read_to_string(dir.join(TIER_MARKER_FILE)).expect("marker"),
            "secret-service\n"
        );
    }

    #[test]
    fn selection_falls_back_when_upper_tiers_fail() {
        let dir = temp_dir("fallback");
        let tiers = [
            KeyringTier::SecretService,
            KeyringTier::DbKeyStore,
            KeyringTier::KeyUtils,
        ];
        let selected = select_with(&dir, &tiers, |tier, dir| {
            if tier == KeyringTier::SecretService {
                failing_factory(tier, dir)
            } else {
                ok_factory(tier, dir)
            }
        })
        .expect("selection");
        assert_eq!(selected.tier, KeyringTier::DbKeyStore);
        assert_eq!(
            std::fs::read_to_string(dir.join(TIER_MARKER_FILE)).expect("marker"),
            "db-keystore\n"
        );
    }

    #[test]
    fn selection_falls_back_when_probe_fails() {
        let dir = temp_dir("probe-fallback");
        let tiers = [
            KeyringTier::SecretService,
            KeyringTier::DbKeyStore,
            KeyringTier::KeyUtils,
        ];
        let selected = select_with(&dir, &tiers, |tier, _dir| {
            let store = mock_store();
            if tier == KeyringTier::SecretService {
                let entry = store
                    .build(SERVICE_NAME, PROBE_USER, None)
                    .expect("probe entry");
                let mock_cred: &mock::Cred = entry
                    .as_any()
                    .downcast_ref()
                    .expect("mock credential downcast");
                mock_cred.set_error(KeyringError::NoStorageAccess(Box::new(
                    std::io::Error::other("simulated locked keyring"),
                )));
            }
            Ok(store)
        })
        .expect("selection");
        assert_eq!(selected.tier, KeyringTier::DbKeyStore);
    }

    #[test]
    fn marker_sticks_to_fallback_tier_even_when_upper_tier_available() {
        let dir = temp_dir("sticky");
        std::fs::write(dir.join(TIER_MARKER_FILE), "db-keystore\n").expect("marker");
        let tiers = [
            KeyringTier::SecretService,
            KeyringTier::DbKeyStore,
            KeyringTier::KeyUtils,
        ];
        let selected = select_with(&dir, &tiers, ok_factory).expect("selection");
        assert_eq!(selected.tier, KeyringTier::DbKeyStore);
    }

    #[test]
    fn selection_fails_when_all_tiers_fail() {
        let dir = temp_dir("all-fail");
        let tiers = [
            KeyringTier::SecretService,
            KeyringTier::DbKeyStore,
            KeyringTier::KeyUtils,
        ];
        let err = select_with(&dir, &tiers, failing_factory).expect_err("selection must fail");
        assert!(err.contains("keyutils"));
        assert!(err.contains("simulated construction failure"));
    }

    #[test]
    fn names_and_secret_are_validated() {
        assert!(validate_names("", "user").is_err());
        assert!(validate_names("service", "").is_err());
        assert!(validate_names(&"s".repeat(MAX_SERVICE_LEN + 1), "user").is_err());
        assert!(validate_names("service", &"u".repeat(MAX_USER_LEN + 1)).is_err());
        assert!(validate_names("service", "user").is_ok());
        assert!(validate_secret(&"x".repeat(MAX_SECRET_LEN + 1)).is_err());
        assert!(validate_secret("ok").is_ok());
    }

    #[test]
    fn tier_strings_round_trip() {
        for tier in [
            KeyringTier::MacOsKeychain,
            KeyringTier::WindowsCredentialManager,
            KeyringTier::SecretService,
            KeyringTier::DbKeyStore,
            KeyringTier::KeyUtils,
        ] {
            assert_eq!(KeyringTier::from_str(tier.as_str()), Some(tier));
        }
        assert_eq!(KeyringTier::from_str("bogus"), None);
    }

    #[test]
    fn fallback_tiers_carry_a_notice() {
        assert!(KeyringTier::MacOsKeychain.notice().is_none());
        assert!(KeyringTier::SecretService.notice().is_none());
        assert!(KeyringTier::DbKeyStore.notice().is_some());
        assert!(KeyringTier::KeyUtils.notice().is_some());
    }
}
